[workspace]
authors = ["AroneyS <samuel.aroney@qut.edu.au>"]
channels = ["conda-forge", "bioconda"]
name = "binchicken"
platforms = ["linux-64"]

[activation]
# Sets metapackage environment variables, which are assumed to be in the db/ of
# the base directory (perhaps symlnked).
scripts = ["admin/set_env_vars.sh"]

[feature.main.dependencies]
python = "3.10.*"
snakemake = "7.32.*"
mamba = "1.4.*"
networkx = "==3.1"
bird_tool_utils_python = "0.4.*"
extern = "0.4.*"
"ruamel.yaml" = ">=0.15.99"
polars = "1.26.*"
pigz = "2.3.*"
pyarrow = "12.0.*"
parallel = "==20230522"
sourmash = "4.8.*"
sourmash_plugin_branchwater = "0.9.*"
# see https://github.com/pyca/cryptography/issues/7959#issuecomment-1368711852
pyopenssl = ">22.1.0"
pixi = "*"

[feature.main.pypi-dependencies]
"binchicken" = { path = ".", editable = true }

[feature.dev.dependencies]
pytest = "*"
ipython = "*"
toml = "*"

[environments]
default = ["main"]
dev = ["dev", "main"]
