[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ibis-genome"
dynamic = ["version"]
authors = [
  { name="Samuel Aroney", email="samuel.aroney@outlook.com" },
]
description = "Ibis (Australian bin chicken) - targeted recovery of low abundance genomes through intelligent coassembly"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
dependencies = ["snakemake>=6.0.5",
  "pandas",
  "biopython",
  "networkx",
  "bird_tool_utils",
  "extern",
  "ruamel.yaml>=0.15.99"]
classifiers = [
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]

[project.urls]
"Homepage" = "https://github.com/AroneyS/ibis"
"Bug Tracker" = "https://github.com/AroneyS/ibis/issues"

[project.scripts]
ibis = "ibis.ibis:main"

[tool.setuptools.dynamic]
version = {attr = "ibis.__version__"}
