# Use a lightweight base image
FROM debian:bullseye-slim

# This dockerfile uses cached mounts, so to build use e.g.
# $ DOCKER_BUILDKIT=1 docker build .

WORKDIR /binchicken

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    git \
    unzip \
    man-db \
    && rm -rf /var/lib/apt/lists/*

# Install Pixi (via install script)
RUN curl -fsSL https://pixi.sh/install.sh | bash

# Add Pixi to PATH
ENV PATH="/root/.pixi/bin:${PATH}"

# re-add the first line when setup here - the second line enables running from arbitrary commits rather than a tag
# RUN git clone https://github.com/AroneyS/binchicken . && git checkout vBINCHICKEN_VERSION
RUN git clone https://github.com/AroneyS/binchicken . && git checkout BINCHICKEN_VERSION

# We install through pip, because installing via pip install -e . causes issues for apptainer
# https://github.com/prefix-dev/pixi/issues/1387
RUN pixi run --no-lockfile-update pip install binchicken==BINCHICKEN_VERSION

# Run binchicken build
RUN binchicken build \
    --singlem-metapackage /binchicken/singlem_metapackage \
    --checkm2-db /binchicken/CheckM2_database \
    --download-databases
ENV SINGLEM_METAPACKAGE_PATH=/binchicken/singlem_metapackage
ENV CHECKM2DB=/binchicken/CheckM2_database

RUN find /binchicken/singlem_metapackage /binchicken/CheckM2_database -type d -print0 | xargs -0 chmod 755
RUN find /binchicken/singlem_metapackage /binchicken/CheckM2_database -type f -print0 | xargs -0 chmod +r
RUN rm -rf /binchicken/build /binchicken/genome_1.fna /binchicken/sample_*
RUN rm -rfv binchicken/.git binchicken/test

# Run some tests
RUN pixi run --frozen binchicken --version
RUN pixi run --frozen binchicken coassemble --full-help | head


# # Remove all the build dependencies / image layers for a smaller image overall
FROM scratch
COPY --from=0 / /

WORKDIR /data
# Add Pixi to PATH
ENV PATH="/root/.pixi/bin:${PATH}"
ENV SINGLEM_METAPACKAGE_PATH=/binchicken/singlem_metapackage
ENV CHECKM2DB=/binchicken/CheckM2_database

RUN pixi shell-hook --frozen --no-install --manifest-path /singlem/pixi.toml |grep -v set_env_vars.sh >>/run_via_pixi.profile
RUN echo 'source /run_via_pixi.profile' >/run_via_pixi.bash
RUN echo 'exec "$@"' >>/run_via_pixi.bash
RUN chmod +x /run_via_pixi.bash

CMD ["bash"]
ENTRYPOINT ["bash", "/run_via_pixi.bash", "binchicken"]
