name: Test Cockatoo with Setup-Miniconda From Marketplace
on: [push]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
        matrix:
            os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: cockatoo.yml
          python-version: 3.9
          auto-activate-base: false
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
      - run: |
          conda info
          conda list
      - name: Install Cockatoo
        run: |
          pip install .
      - name: Run pytest
        run: |
            python test/test_cluster.py && \
            python test/test_coassemble.py && \
            python test/test_evaluate.py
