name: Test Ibis with Setup-Miniconda From Marketplace
on: [push]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
        matrix:
            python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment with Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: ibis.yml
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Mambaforge
          auto-activate-base: false
          channels: conda-forge,bioconda
          channel-priority: true
      - run: |
          conda info
          conda list
          conda config --set channel_priority strict
      - name: Install Ibis
        run: |
          pip install -e .
      - name: Run unit tests
        run: |
          python test/test_query_processing.py
          #python test/test_target_elusive.py
          python test/test_cluster_graph.py -b
          python test/test_collect_reference_bins.py
          python test/test_unmap.py
          python test/test_evaluate.py
          python test/test_evaluate_script.py
          python test/test_evaluate_Rscript.py -b
          python test/test_coassemble.py
